### ISSUE TITLE
Unable to apply allow_caps to Docker config under nomad_plugins

### ISSUE THREAD

**Issue by bradleydwyer** [ansible-community/ansible-nomad#127]
Was just trying to add the a capability to the Docker plugin (in my case, NET_ADMIN) and noticed that the generated client.hcl isn't accepted by Nomad on startup.

Given the Ansible YAML config of:
```
nomad_plugins:
  docker:
    config:
      allow_caps: ["NET_ADMIN"]
```

The generated HCL is (that Nomad rejects):
```
plugin "docker" {
    config {
        allow_caps = ['net_admin']
    }
}
```
Where I would have expected (and Nomad happily starts with):
```
plugin "docker" {
    config {
        allow_caps = ["NET_ADMIN"]
    }
}
```

I also tried a list format for the YAML
```
nomad_plugins:
  docker:
    config:
      allow_caps:
      - "NET_ADMIN"
```

But it had the same output.

I presume the lowercase originates from https://github.com/ansible-community/ansible-nomad/blob/a1853f1cf1051f72ca4b3fc672a56686b42efce6/templates/client.hcl.j2#L74 and I'm happy to change it, but I'm not sure why it's there in the first place, so I'm a little hesitant to just go changing it to solve my specific problem.
